"""Alert formatting and notification safety for actionable Solana trades."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Mapping

from .decision import DecisionResult
from .models import Decision, TokenAnalysis


@dataclass(frozen=True)
class Alert:
    """Immutable notification payload."""

    text: str
    contract_address: str


class NotificationError(ValueError):
    """Raised when an alert cannot be safely constructed or delivered."""


def build_alert(analysis: TokenAnalysis, decision: DecisionResult) -> Alert | None:
    """Build an actionable alert, preserving the exact verified mint address.

    No alert is returned unless the decision is BUY_CANDIDATE and the decision
    result agrees with the analysis score/confidence. The contract address is
    taken directly from TokenMarketData and is never generated by the AI.
    """
    if decision.decision is not Decision.BUY_CANDIDATE:
        return None
    if not decision.actionable:
        raise NotificationError("Decision is marked non-actionable")
    if decision.score < 85 or decision.confidence < 85:
        raise NotificationError("Actionable alert requires score and confidence >= 85")

    address = analysis.token.address
    if not address or address != analysis.contract_address:
        raise NotificationError("Verified contract address is missing or inconsistent")

    # Explicit integrity check: the address shown in the alert must be exactly
    # the mint address carried by the validated analysis object.
    # Telegram receives HTML parse mode, so the mint is rendered as a dedicated
    # code span that makes the full address easy to select/copy without changing
    # the underlying contract value.
    text = "\n".join(
        [
            "🚨 SOLANA UTILITY TRADE CANDIDATE",
            "",
            f"Token: {analysis.token.name} (${analysis.token.symbol})",
            f"Contract / Mint Address: <code>{address}</code>",
            f"Market Cap: ${analysis.token.market_cap_usd:,.0f}",
            f"Liquidity: ${analysis.token.liquidity_usd:,.0f}",
            f"24h Volume: ${analysis.token.volume_24h_usd:,.0f}",
            f"Opportunity Score: {decision.score:.2f}/100",
            f"Confidence: {decision.confidence:.2f}%",
            "",
            "Decision: 🟢 BUY CANDIDATE",
            f"Why Now: {analysis.why_now}",
            "",
            "Key Risks:",
            *([f"- {reason}" for reason in analysis.risk.reasons] or ["- No specific risk reason recorded"]),
            "",
            "Invalidation Conditions:",
            *([f"- {item}" for item in analysis.invalidation_conditions] or ["- None recorded"]),
        ]
    )

    if address not in text:
        raise NotificationError("Contract address integrity check failed")

    return Alert(text=text, contract_address=address)


def send_alert(alert: Alert, sender: Callable[[str], object]) -> object:
    """Send an already-validated alert through a provider callback."""
    if not alert.contract_address or alert.contract_address not in alert.text:
        raise NotificationError("Refusing to send an alert without its exact contract address")
    return sender(alert.text)


def telegram_payload(alert: Alert) -> Mapping[str, str]:
    """Return a provider-neutral Telegram-style payload."""
    if not alert.contract_address or alert.contract_address not in alert.text:
        raise NotificationError("Invalid alert payload")
    return {"text": alert.text, "parse_mode": "HTML"}
